CREATE TYPE status_type AS ENUM (
  'OPERATIONAL',
  'DEGRADED',
  'OUTAGE'
);

CREATE TYPE component_type AS ENUM (
  'BACKEND_JAVA',
  'BACKEND_PYTHON',
  'FRONTEND_ANGULAR'
);

CREATE TABLE products (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar(100) UNIQUE NOT NULL,
  "description" text,
  "display_order" integer DEFAULT 0,
  "is_visible" boolean DEFAULT true,
  "created_at" timestamp DEFAULT (now()),
  "updated_at" timestamp DEFAULT (now())
);

CREATE TABLE components (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "product_id" bigint NOT NULL,
  "parent_component_id" bigint,

  "name" varchar(100) NOT NULL,
  "description" text,
  "type" component_type NOT NULL,
  "current_status" status_type NOT NULL DEFAULT 'OPERATIONAL',
  "status_changed_at" timestamp DEFAULT (now()),

  "health_url" varchar(500),
  "check_interval_seconds" integer DEFAULT 60,
  "timeout_seconds" integer DEFAULT 30,
  "expected_status_code" integer DEFAULT 200,
  "max_response_time_ms" integer DEFAULT 5000,
  "failures_before_outage" integer DEFAULT 3,

  "is_active" boolean DEFAULT true,
  "last_checked_at" timestamp,
  "consecutive_failures" integer DEFAULT 0,
  "display_order" integer DEFAULT 0,

  "created_at" timestamp DEFAULT (now()),
  "updated_at" timestamp DEFAULT (now()),

  constraint fk_components_products
  foreign key (product_id)
  references products(id),

  constraint fk_parent_components
  foreign key (parent_component_id)
  references components(parent_component_id)
);

CREATE TABLE health_checks (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "component_id" bigint NOT NULL,

  "checked_at" timestamp NOT NULL DEFAULT (now()),
  "is_successful" boolean NOT NULL,
  "status_code" integer,
  "response_time_ms" integer,
  "status_before" status_type,
  "status_after" status_type,
  "error_message" text,

  constraint fk_health_check_component
  foreign key (component_id)
  references components(component_id)
);

CREATE INDEX ON products ("name");
CREATE INDEX ON products ("display_order");
CREATE INDEX ON components ("product_id");
CREATE INDEX ON components ("parent_component_id");
CREATE INDEX ON components ("type");
CREATE INDEX ON components ("current_status");
CREATE INDEX ON components ("is_active", "last_checked_at");
CREATE INDEX ON health_checks ("component_id");
CREATE INDEX ON health_checks ("checked_at");
CREATE INDEX ON health_checks ("component_id", "checked_at");
